=== zlpmichelle/BigValue/conf/index-conf.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="columnFamily" type="xs:string"/>
    <xs:attribute name="qualifier" type="xs:string"/>
    <xs:attribute name="maxLength" type="xs:integer"/>
    <xs:attribute name="isLengthVariable" type="xs:boolean"/>
    <xs:attribute name="isOrderInverted" type="xs:boolean"/>
    <xs:attribute name="formatter" type="xs:string"/>

    <xs:element name="indexes">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="index">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="table" type="xs:string"/>
                            <xs:choice minOccurs="1" maxOccurs="1">
                                <xs:element name="fields">
                                    <xs:complexType>
                                        <xs:choice minOccurs="1" maxOccurs="unbounded">
                                            <xs:element name="field">
                                                <xs:complexType>
                                                    <xs:attribute ref="columnFamily" use="required"/>
                                                    <xs:attribute ref="qualifier" use="required"/>
                                                    <xs:attribute ref="maxLength" use="required"/>
                                                    <xs:attribute ref="isLengthVariable" use="required"/>
                                                    <xs:attribute ref="isOrderInverted" use="required"/>
                                                    <xs:attribute ref="formatter" use="optional"/>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:choice>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== zlpmichelle/BigValue/examples/CDH5.0/conf/test_index-conf.xml
<?xml version="1.0" encoding="UTF-8"?>

<indexes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="index-conf.xsd">
    <index>
        <name>a</name>
        <table>test</table>
        <fields>
            <field columnFamily="f" qualifier="q1" maxLength="20" isLengthVariable="true" isOrderInverted="false"
                   formatter="com.cloudera.bigdata.analysis.index.formatter.LengthVariableValueFormatter"/>
        </fields>
    </index>    
    <index>
        <name>b</name>
        <table>test</table>
        <fields>
            <field columnFamily="f" qualifier="q2" maxLength="16" isLengthVariable="false" isOrderInverted="false"/>
            <field columnFamily="f" qualifier="q3" maxLength="16" isLengthVariable="false" isOrderInverted="false"/>
        </fields>
    </index>
    <index>
        <name>c</name>
        <table>test</table>
        <fields>
            <field columnFamily="f" qualifier="q4" maxLength="20" isLengthVariable="true" isOrderInverted="false"
                   formatter="com.cloudera.bigdata.analysis.index.formatter.LengthVariableValueFormatter"/>
        </fields>
    </index>
</indexes>

=== zlpmichelle/BigValue/examples/Parallel_Scalability_Test/conf/1tb_index-conf.xml
<?xml version="1.0" encoding="UTF-8"?>

<indexes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="index-conf.xsd">
    <index>
        <name>a</name>
        <table>1tb</table>
        <fields>
            <field columnFamily="f" qualifier="q1" maxLength="6" isLengthVariable="true" isOrderInverted="false"
                   formatter="com.cloudera.bigdata.analysis.dataload.index.formatter.LengthVariableValueFormatter"/>
        </fields>
    </index>    
    <index>
        <name>b</name>
        <table>1tb</table>
        <fields>
            <field columnFamily="f" qualifier="q2" maxLength="8" isLengthVariable="false" isOrderInverted="false"/>
        </fields>
    </index>
    <index>
        <name>c</name>
        <table>1tb</table>
        <fields>
            <field columnFamily="f" qualifier="q3" maxLength="6" isLengthVariable="true" isOrderInverted="false"
                   formatter="com.cloudera.bigdata.analysis.dataload.index.formatter.LengthVariableValueFormatter"/>
        </fields>
    </index>
    <index>
        <name>d</name>
        <table>1tb</table>
        <fields>
            <field columnFamily="f" qualifier="q4" maxLength="11" isLengthVariable="false" isOrderInverted="false"/>
        </fields>
    </index>
    <index>
        <name>e</name>
        <table>1tb</table>
        <fields>
            <field columnFamily="f" qualifier="q1" maxLength="6" isLengthVariable="true" isOrderInverted="false"
                   formatter="com.cloudera.bigdata.analysis.dataload.index.formatter.LengthVariableValueFormatter"/>
            <field columnFamily="f" qualifier="q3" maxLength="6" isLengthVariable="true" isOrderInverted="false"
                   formatter="com.cloudera.bigdata.analysis.dataload.index.formatter.LengthVariableValueFormatter"/>
        </fields>
    </index>
    <index>
        <name>f</name>
        <table>1tb</table>
        <fields>
            <field columnFamily="f" qualifier="q2" maxLength="8" isLengthVariable="false" isOrderInverted="false"/>
            <field columnFamily="f" qualifier="q4" maxLength="11" isLengthVariable="false" isOrderInverted="false"/>
        </fields>
    </index>
    <index>
        <name>g</name>
        <table>1tb</table>
        <fields>
            <field columnFamily="f" qualifier="q1" maxLength="6" isLengthVariable="true" isOrderInverted="false"
                   formatter="com.cloudera.bigdata.analysis.dataload.index.formatter.LengthVariableValueFormatter"/>
            <field columnFamily="f" qualifier="q2" maxLength="8" isLengthVariable="false" isOrderInverted="false"/>
            <field columnFamily="f" qualifier="q4" maxLength="11" isLengthVariable="false" isOrderInverted="false"/>
        </fields>
    </index>
    <index>
        <name>h</name>
        <table>1tb</table>
        <fields>
            <field columnFamily="f" qualifier="q2" maxLength="8" isLengthVariable="false" isOrderInverted="false"/>
            <field columnFamily="f" qualifier="q3" maxLength="6" isLengthVariable="true" isOrderInverted="false"
                   formatter="com.cloudera.bigdata.analysis.dataload.index.formatter.LengthVariableValueFormatter"/>
            <field columnFamily="f" qualifier="q4" maxLength="11" isLengthVariable="false" isOrderInverted="false"/>
        </fields>
    </index>
</indexes>
